default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: application_tracker_development

test:
  <<: *default
  database: application_tracker_test

production:
  <<: *default
  database: application_tracker_production
  username: application_tracker
  password: <%= ENV["APPLICATION_TRACKER_DATABASE_PASSWORD"] %>
